# Generated by Django 5.2 on 2025-04-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=10)),
                ('inicio', models.JSONField()),
                ('fin', models.JSONField()),
                ('muros', models.JSONField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
